# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'teknappi' do
pod 'Argo'
pod 'SnapKit'
pod 'RxSwift', '2.0.0-alpha.3'
pod 'RxCocoa', '2.0.0-alpha.3'
end

